/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    partners: Partner;
    events: Event;
    users: User;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('de' | 'en') | ('de' | 'en')[];
  globals: {
    navigation: Navigation;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'de' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  layout?:
    | (
        | {
            visible?: boolean | null;
            headline?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            description?: string | null;
            primaryCtaText?: string | null;
            textColor?: string | null;
            backgroundColor?: string | null;
            primaryCtaLink?: {
              type?: ('internal' | 'external') | null;
              page?: (number | null) | Page;
              url?: string | null;
              /**
               * z. B. programs oder apply (ohne #)
               */
              anchor?: string | null;
              newTab?: boolean | null;
            };
            heroImage?: (number | null) | Media;
            heroImageTablet?: (number | null) | Media;
            heroImageMobile?: (number | null) | Media;
            quickAccessCards?:
              | {
                  title?: string | null;
                  variant?: ('brand' | 'accent') | null;
                  position?: ('left' | 'right') | null;
                  link?: {
                    type?: ('internal' | 'external') | null;
                    page?: (number | null) | Page;
                    url?: string | null;
                    /**
                     * z. B. programs oder apply (ohne #)
                     */
                    anchor?: string | null;
                    newTab?: boolean | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            visible?: boolean | null;
            tagline?: string | null;
            headline?: string | null;
            description?: string | null;
            ctaText?: string | null;
            ctaLink?: {
              type?: ('internal' | 'external') | null;
              page?: (number | null) | Page;
              url?: string | null;
              /**
               * z. B. programs oder apply (ohne #)
               */
              anchor?: string | null;
              newTab?: boolean | null;
            };
            cards?:
              | {
                  title?: string | null;
                  description?: string | null;
                  icon?: (number | null) | Media;
                  backgroundColor?: string | null;
                  textColor?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'benefitsBento';
          }
        | {
            visible?: boolean | null;
            tagline?: string | null;
            headline?: string | null;
            description?: string | null;
            ctaText?: string | null;
            sectionId?: string | null;
            ctaLink?: {
              type?: ('internal' | 'external') | null;
              page?: (number | null) | Page;
              url?: string | null;
              /**
               * z. B. programs oder apply (ohne #)
               */
              anchor?: string | null;
              newTab?: boolean | null;
            };
            programs?:
              | {
                  title?: string | null;
                  description?: string | null;
                  stageLabel?: string | null;
                  backgroundColor?: string | null;
                  image?: (number | null) | Media;
                  imageTablet?: (number | null) | Media;
                  imageMobile?: (number | null) | Media;
                  link?: {
                    type?: ('internal' | 'external') | null;
                    page?: (number | null) | Page;
                    url?: string | null;
                    /**
                     * z. B. programs oder apply (ohne #)
                     */
                    anchor?: string | null;
                    newTab?: boolean | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'programsSection';
          }
        | {
            visible?: boolean | null;
            tagline?: string | null;
            headline?: string | null;
            description?: string | null;
            ctaText?: string | null;
            ctaLink?: {
              type?: ('internal' | 'external') | null;
              page?: (number | null) | Page;
              url?: string | null;
              /**
               * z. B. programs oder apply (ohne #)
               */
              anchor?: string | null;
              newTab?: boolean | null;
            };
            challenges?:
              | {
                  title?: string | null;
                  category?: string | null;
                  description?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  ctaText?: string | null;
                  ctaLink?: {
                    type?: ('internal' | 'external') | null;
                    page?: (number | null) | Page;
                    url?: string | null;
                    /**
                     * z. B. programs oder apply (ohne #)
                     */
                    anchor?: string | null;
                    newTab?: boolean | null;
                  };
                  featuredImage?: (number | null) | Media;
                  featuredImageTablet?: (number | null) | Media;
                  featuredImageMobile?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'challengesSection';
          }
        | {
            visible?: boolean | null;
            tagline?: string | null;
            headline?: string | null;
            subtitle?: string | null;
            description?: string | null;
            backgroundStyle?: string | null;
            tab1Label?: string | null;
            tab2Label?: string | null;
            tab1Cards?:
              | {
                  title?: string | null;
                  description?: string | null;
                  icon?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            tab2Cards?:
              | {
                  title?: string | null;
                  description?: string | null;
                  icon?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'whyJoinUsSection';
          }
        | {
            visible?: boolean | null;
            tagline?: string | null;
            headline?: string | null;
            subtitle?: string | null;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            ctaText?: string | null;
            sliderLabel?: string | null;
            ctaLink?: {
              type?: ('internal' | 'external') | null;
              page?: (number | null) | Page;
              url?: string | null;
              /**
               * z. B. programs oder apply (ohne #)
               */
              anchor?: string | null;
              newTab?: boolean | null;
            };
            topics?:
              | {
                  title?: string | null;
                  cardTitle?: string | null;
                  cardDescription?: string | null;
                  linkText?: string | null;
                  accentColor?: string | null;
                  link?: {
                    type?: ('internal' | 'external') | null;
                    page?: (number | null) | Page;
                    url?: string | null;
                    /**
                     * z. B. programs oder apply (ohne #)
                     */
                    anchor?: string | null;
                    newTab?: boolean | null;
                  };
                  image?: (number | null) | Media;
                  imageTablet?: (number | null) | Media;
                  imageMobile?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'keyTopicsSliderSection';
          }
        | {
            visible?: boolean | null;
            tagline?: string | null;
            title?: string | null;
            subtitle?: string | null;
            ctaText?: string | null;
            rowCount?: string | null;
            backgroundColor?: string | null;
            ctaLink?: {
              type?: ('internal' | 'external') | null;
              page?: (number | null) | Page;
              url?: string | null;
              /**
               * z. B. programs oder apply (ohne #)
               */
              anchor?: string | null;
              newTab?: boolean | null;
            };
            logos?:
              | {
                  name?: string | null;
                  logo?: (number | null) | Media;
                  partner?: (number | null) | Partner;
                  link?: {
                    type?: ('internal' | 'external') | null;
                    page?: (number | null) | Page;
                    url?: string | null;
                    /**
                     * z. B. programs oder apply (ohne #)
                     */
                    anchor?: string | null;
                    newTab?: boolean | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homepagePartnersSection';
          }
        | {
            visible?: boolean | null;
            tagline?: string | null;
            headline?: string | null;
            description?: string | null;
            ctaText?: string | null;
            textColor?: string | null;
            ctaLink?: {
              type?: ('internal' | 'external') | null;
              page?: (number | null) | Page;
              url?: string | null;
              /**
               * z. B. programs oder apply (ohne #)
               */
              anchor?: string | null;
              newTab?: boolean | null;
            };
            layers?:
              | {
                  label?: string | null;
                  position?: ('left' | 'right') | null;
                  textColor?: string | null;
                  backgroundColor?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ecosystemDiagramSection';
          }
        | {
            visible?: boolean | null;
            tagline?: string | null;
            headline?: string | null;
            subtitle?: string | null;
            description?: string | null;
            ctaText?: string | null;
            ctaLink?: {
              type?: ('internal' | 'external') | null;
              page?: (number | null) | Page;
              url?: string | null;
              /**
               * z. B. programs oder apply (ohne #)
               */
              anchor?: string | null;
              newTab?: boolean | null;
            };
            maxEvents?: number | null;
            selectionMode?: ('automatic' | 'manual') | null;
            selectedEvents?: (number | Event)[] | null;
            events?:
              | {
                  title?: string | null;
                  date?: string | null;
                  location?: string | null;
                  hostedBy?: string | null;
                  tags?: string | null;
                  colorTheme?: ('pink' | 'blue' | 'light-blue') | null;
                  ctaText?: string | null;
                  image?: (number | null) | Media;
                  link?: {
                    type?: ('internal' | 'external') | null;
                    page?: (number | null) | Page;
                    url?: string | null;
                    /**
                     * z. B. programs oder apply (ohne #)
                     */
                    anchor?: string | null;
                    newTab?: boolean | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homepageEventsSection';
          }
        | {
            visible?: boolean | null;
            tagline?: string | null;
            title?: string | null;
            subtitle?: string | null;
            ctaText?: string | null;
            ctaLink?: {
              type?: ('internal' | 'external') | null;
              page?: (number | null) | Page;
              url?: string | null;
              /**
               * z. B. programs oder apply (ohne #)
               */
              anchor?: string | null;
              newTab?: boolean | null;
            };
            sectionId?: string | null;
            imageFit?: string | null;
            imagePosition?: string | null;
            image?: (number | null) | Media;
            mobileImage?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaSection';
          }
      )[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  slug: string;
  /**
   * Import-Referenz
   */
  storyblokUuid?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: string | null;
  sourceUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    desktop?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  slug?: string | null;
  logo?: (number | null) | Media;
  website?: string | null;
  description?: string | null;
  storyblokUuid?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug?: string | null;
  date?: string | null;
  location?: string | null;
  hostedBy?: string | null;
  tags?: string | null;
  image?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  storyblokUuid?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              visible?: T;
              headline?: T;
              description?: T;
              primaryCtaText?: T;
              textColor?: T;
              backgroundColor?: T;
              primaryCtaLink?:
                | T
                | {
                    type?: T;
                    page?: T;
                    url?: T;
                    anchor?: T;
                    newTab?: T;
                  };
              heroImage?: T;
              heroImageTablet?: T;
              heroImageMobile?: T;
              quickAccessCards?:
                | T
                | {
                    title?: T;
                    variant?: T;
                    position?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          page?: T;
                          url?: T;
                          anchor?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        benefitsBento?:
          | T
          | {
              visible?: T;
              tagline?: T;
              headline?: T;
              description?: T;
              ctaText?: T;
              ctaLink?:
                | T
                | {
                    type?: T;
                    page?: T;
                    url?: T;
                    anchor?: T;
                    newTab?: T;
                  };
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    backgroundColor?: T;
                    textColor?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        programsSection?:
          | T
          | {
              visible?: T;
              tagline?: T;
              headline?: T;
              description?: T;
              ctaText?: T;
              sectionId?: T;
              ctaLink?:
                | T
                | {
                    type?: T;
                    page?: T;
                    url?: T;
                    anchor?: T;
                    newTab?: T;
                  };
              programs?:
                | T
                | {
                    title?: T;
                    description?: T;
                    stageLabel?: T;
                    backgroundColor?: T;
                    image?: T;
                    imageTablet?: T;
                    imageMobile?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          page?: T;
                          url?: T;
                          anchor?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        challengesSection?:
          | T
          | {
              visible?: T;
              tagline?: T;
              headline?: T;
              description?: T;
              ctaText?: T;
              ctaLink?:
                | T
                | {
                    type?: T;
                    page?: T;
                    url?: T;
                    anchor?: T;
                    newTab?: T;
                  };
              challenges?:
                | T
                | {
                    title?: T;
                    category?: T;
                    description?: T;
                    ctaText?: T;
                    ctaLink?:
                      | T
                      | {
                          type?: T;
                          page?: T;
                          url?: T;
                          anchor?: T;
                          newTab?: T;
                        };
                    featuredImage?: T;
                    featuredImageTablet?: T;
                    featuredImageMobile?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        whyJoinUsSection?:
          | T
          | {
              visible?: T;
              tagline?: T;
              headline?: T;
              subtitle?: T;
              description?: T;
              backgroundStyle?: T;
              tab1Label?: T;
              tab2Label?: T;
              tab1Cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              tab2Cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        keyTopicsSliderSection?:
          | T
          | {
              visible?: T;
              tagline?: T;
              headline?: T;
              subtitle?: T;
              description?: T;
              ctaText?: T;
              sliderLabel?: T;
              ctaLink?:
                | T
                | {
                    type?: T;
                    page?: T;
                    url?: T;
                    anchor?: T;
                    newTab?: T;
                  };
              topics?:
                | T
                | {
                    title?: T;
                    cardTitle?: T;
                    cardDescription?: T;
                    linkText?: T;
                    accentColor?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          page?: T;
                          url?: T;
                          anchor?: T;
                          newTab?: T;
                        };
                    image?: T;
                    imageTablet?: T;
                    imageMobile?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        homepagePartnersSection?:
          | T
          | {
              visible?: T;
              tagline?: T;
              title?: T;
              subtitle?: T;
              ctaText?: T;
              rowCount?: T;
              backgroundColor?: T;
              ctaLink?:
                | T
                | {
                    type?: T;
                    page?: T;
                    url?: T;
                    anchor?: T;
                    newTab?: T;
                  };
              logos?:
                | T
                | {
                    name?: T;
                    logo?: T;
                    partner?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          page?: T;
                          url?: T;
                          anchor?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ecosystemDiagramSection?:
          | T
          | {
              visible?: T;
              tagline?: T;
              headline?: T;
              description?: T;
              ctaText?: T;
              textColor?: T;
              ctaLink?:
                | T
                | {
                    type?: T;
                    page?: T;
                    url?: T;
                    anchor?: T;
                    newTab?: T;
                  };
              layers?:
                | T
                | {
                    label?: T;
                    position?: T;
                    textColor?: T;
                    backgroundColor?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        homepageEventsSection?:
          | T
          | {
              visible?: T;
              tagline?: T;
              headline?: T;
              subtitle?: T;
              description?: T;
              ctaText?: T;
              ctaLink?:
                | T
                | {
                    type?: T;
                    page?: T;
                    url?: T;
                    anchor?: T;
                    newTab?: T;
                  };
              maxEvents?: T;
              selectionMode?: T;
              selectedEvents?: T;
              events?:
                | T
                | {
                    title?: T;
                    date?: T;
                    location?: T;
                    hostedBy?: T;
                    tags?: T;
                    colorTheme?: T;
                    ctaText?: T;
                    image?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          page?: T;
                          url?: T;
                          anchor?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaSection?:
          | T
          | {
              visible?: T;
              tagline?: T;
              title?: T;
              subtitle?: T;
              ctaText?: T;
              ctaLink?:
                | T
                | {
                    type?: T;
                    page?: T;
                    url?: T;
                    anchor?: T;
                    newTab?: T;
                  };
              sectionId?: T;
              imageFit?: T;
              imagePosition?: T;
              image?: T;
              mobileImage?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  slug?: T;
  storyblokUuid?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  sourceUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        desktop?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  website?: T;
  description?: T;
  storyblokUuid?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  date?: T;
  location?: T;
  hostedBy?: T;
  tags?: T;
  image?: T;
  description?: T;
  storyblokUuid?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  logo?: (number | null) | Media;
  logoText?: string | null;
  sticky?: boolean | null;
  showLanguageSwitcher?: boolean | null;
  logoLink?: {
    type?: ('internal' | 'external') | null;
    page?: (number | null) | Page;
    url?: string | null;
    /**
     * z. B. programs oder apply (ohne #)
     */
    anchor?: string | null;
    newTab?: boolean | null;
  };
  menuItems?:
    | {
        label?: string | null;
        link?: {
          type?: ('internal' | 'external') | null;
          page?: (number | null) | Page;
          url?: string | null;
          /**
           * z. B. programs oder apply (ohne #)
           */
          anchor?: string | null;
          newTab?: boolean | null;
        };
        hasDropdown?: boolean | null;
        dropdownItems?:
          | {
              label?: string | null;
              link?: {
                type?: ('internal' | 'external') | null;
                page?: (number | null) | Page;
                url?: string | null;
                /**
                 * z. B. programs oder apply (ohne #)
                 */
                anchor?: string | null;
                newTab?: boolean | null;
              };
              subItems?:
                | {
                    label?: string | null;
                    link?: {
                      type?: ('internal' | 'external') | null;
                      page?: (number | null) | Page;
                      url?: string | null;
                      /**
                       * z. B. programs oder apply (ohne #)
                       */
                      anchor?: string | null;
                      newTab?: boolean | null;
                    };
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaButton?: {
    label?: string | null;
    variant?: ('primary' | 'secondary') | null;
    link?: {
      type?: ('internal' | 'external') | null;
      page?: (number | null) | Page;
      url?: string | null;
      /**
       * z. B. programs oder apply (ohne #)
       */
      anchor?: string | null;
      newTab?: boolean | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  showNavbar?: boolean | null;
  showFooter?: boolean | null;
  hideNavbarRoutes?: string | null;
  hideFooterRoutes?: string | null;
  footer?: {
    logo?: (number | null) | Media;
    copyrightText?: string | null;
    columns?:
      | {
          title?: string | null;
          links?:
            | {
                link?: {
                  label?: string | null;
                  type?: ('internal' | 'external') | null;
                  page?: (number | null) | Page;
                  url?: string | null;
                  /**
                   * z. B. programs oder apply (ohne #)
                   */
                  anchor?: string | null;
                  newTab?: boolean | null;
                };
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    legalLinks?:
      | {
          link?: {
            label?: string | null;
            type?: ('internal' | 'external') | null;
            page?: (number | null) | Page;
            url?: string | null;
            /**
             * z. B. programs oder apply (ohne #)
             */
            anchor?: string | null;
            newTab?: boolean | null;
          };
          id?: string | null;
        }[]
      | null;
    socialLinks?:
      | {
          link?: {
            label?: string | null;
            type?: ('internal' | 'external') | null;
            page?: (number | null) | Page;
            url?: string | null;
            /**
             * z. B. programs oder apply (ohne #)
             */
            anchor?: string | null;
            newTab?: boolean | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  newsletter?: {
    show?: boolean | null;
    title?: string | null;
    text?: string | null;
    buttonText?: string | null;
    embedCode?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  logo?: T;
  logoText?: T;
  sticky?: T;
  showLanguageSwitcher?: T;
  logoLink?:
    | T
    | {
        type?: T;
        page?: T;
        url?: T;
        anchor?: T;
        newTab?: T;
      };
  menuItems?:
    | T
    | {
        label?: T;
        link?:
          | T
          | {
              type?: T;
              page?: T;
              url?: T;
              anchor?: T;
              newTab?: T;
            };
        hasDropdown?: T;
        dropdownItems?:
          | T
          | {
              label?: T;
              link?:
                | T
                | {
                    type?: T;
                    page?: T;
                    url?: T;
                    anchor?: T;
                    newTab?: T;
                  };
              subItems?:
                | T
                | {
                    label?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          page?: T;
                          url?: T;
                          anchor?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  ctaButton?:
    | T
    | {
        label?: T;
        variant?: T;
        link?:
          | T
          | {
              type?: T;
              page?: T;
              url?: T;
              anchor?: T;
              newTab?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  showNavbar?: T;
  showFooter?: T;
  hideNavbarRoutes?: T;
  hideFooterRoutes?: T;
  footer?:
    | T
    | {
        logo?: T;
        copyrightText?: T;
        columns?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          label?: T;
                          type?: T;
                          page?: T;
                          url?: T;
                          anchor?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
        legalLinks?:
          | T
          | {
              link?:
                | T
                | {
                    label?: T;
                    type?: T;
                    page?: T;
                    url?: T;
                    anchor?: T;
                    newTab?: T;
                  };
              id?: T;
            };
        socialLinks?:
          | T
          | {
              link?:
                | T
                | {
                    label?: T;
                    type?: T;
                    page?: T;
                    url?: T;
                    anchor?: T;
                    newTab?: T;
                  };
              id?: T;
            };
      };
  newsletter?:
    | T
    | {
        show?: T;
        title?: T;
        text?: T;
        buttonText?: T;
        embedCode?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}